name: Deploy App

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행
  pull_request:
    branches:
      - main  # main 브랜치에 풀 리퀘스트가 있을 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions가 실행될 환경

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 저장소에서 코드 체크아웃

    - name: Set up Python
      uses: actions/setup-python@v2  # Python 환경 설정
      with:
        python-version: '3.x'  # 사용하고 싶은 Python 버전

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requirements.txt에 기록된 의존성 설치

    - name: Run tests
      run: |
        python -m unittest discover  # 테스트 실행 (필요한 경우 테스트 설정)

    - name: Deploy to production
      run: |
        # SSH를 통해 서버에 접속하여 배포 명령 실행
        ssh user@yourserver "cd /path/to/your/app && git pull && systemctl restart your-app-service"  # 예시 배포 명령
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 비공개 SSH 키를 GitHub Secrets에 저장하여 사용

    - name: Notify Deployment Success
      run: |
        curl -X POST --data-urlencode "payload={'text': '배포가 성공적으로 완료되었습니다.'}" YOUR_SLACK_WEBHOOK_URL  # Slack 알림
